./db_bench \
--fs_uri=zenfs://dev:nvme0n1 \
--benchmarks=fillrandom,stats \
--num=50000000 \
--key_size=16 \
--value_size=1024 \
--block_size=4096 \
--compression_type="none" \
--max_background_compactions=1 \
--max_background_flushes=1 \
--statistics \
--block_align=true > test_5000_reuse_2.log
